In [1]:
# Dependencies and Setup
import pandas as pd
import matplotlib.pyplot as plt
import pymongo
pd.set_option('display.max_columns',200,'display.max_rows', 1000)

prog_dtl = "Resources/chi_prog_geo_data_7_14_2021.csv"
comm_dtl = "Resources/ReferenceCCAProfiles20152019.csv"

# Read Program and Community Survey Data Files and store into Pandas DataFrames
full_prog_data = pd.read_csv(prog_dtl)
full_comm_data = pd.read_csv(comm_dtl)

C:\Users\Mighel\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (14) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [2]:
# Initialize PyMongo to work with MongoDBs
conn = 'mongodb+srv://admin:admin@cluster0.5lstl.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'
client = pymongo.MongoClient(conn)

In [3]:
full_prog_data.shape

(4676, 133)

In [4]:
full_prog_data.columns

Index(['id', 'address', 'audience_2_5', 'audience_5_8', 'audience_8_12',
       'audience_12_16', 'audience_16_19', 'audience_19_24', 'city',
       'created_by',
       ...
       'program_provides_free_food', 'program_pays_participants',
       'program_provides_transportation', 'program_created_at',
       'program_updated_at', 'site_id.1', 'col_program_id', 'category_id',
       'col_cluster_id', 'col_org_id'],
      dtype='object', length=133)

In [5]:
for columns in full_prog_data.columns:
    print(columns)

id
address
audience_2_5
audience_5_8
audience_8_12
audience_12_16
audience_16_19
audience_19_24
city
created_by
description
end_date
end_time
hide
hide_reason
hidden_by
latitude_old
location_name
logo_url
longitude_old
meeting_type
name
online_address
org_id
org_name
program_type
program_id
registration_deadline
registration_url
scheduled_mon
scheduled_tues
scheduled_wed
scheduled_thurs
scheduled_fri
scheduled_sat
scheduled_sun
site_id
start_date
start_time
state
updated_by
zipcode
created_at
updated_at
contact_name
contact_email
contact_phone
program_url
neighborhood
reverse_address
price
min_age
max_age
external_id
level_id
claim_code
extra_data
latitude
longitude
capacity
community
ward
public
internal_id
dosage
location_id
mon_start_time
mon_end_time
tues_start_time
tues_end_time
wed_start_time
wed_end_time
thurs_start_time
thurs_end_time
fri_start_time
fri_end_time
sat_start_time
sat_end_time
sun_start_time
sun_end_time
participants_paid
transport_provided
schedule_type
registration_open
scholarship_available
has_free_food
rrule
site_name
org_name.1
program_name
program_location_name
is_distinct_program_location_name
geographic_cluster_name
is_default_cluster
category_name
program_sub_categories
program_sub_category_ids
cluster_link_deleted
program_claim_code
program_registration_deadline
program_start_date
program_end_date
program_start_time
program_end_time
program_start_time_military
program_end_time_military
program_price
program_meeting_type
program_address
program_city
program_state
program_zip_code
program_latitude
program_longitude
user_entered_program_address
user_entered_program_city
user_entered_program_state
user_entered_program_zip_code
program_min_age
program_max_age
program_capacity
program_dosage
program_has_scholarships
program_provides_free_food
program_pays_participants
program_provides_transportation
program_created_at
program_updated_at
site_id.1
col_program_id
category_id
col_cluster_id
col_org_id

In [6]:
full_comm_data.shape

(104, 245)

In [7]:
full_comm_data.columns

Index(['GEOID', 'GEOG', '2000_POP', '2010_POP', 'TOT_POP', 'UND5', 'A5_19',
       'A20_34', 'A35_49', 'A50_64',
       ...
       '2000_ASSOC', '2000_BACH', '2000_GRAD_PROF', '2000_POP_25OV',
       'HT_Cost_Typical', 'HT_Cost_Mod', 'H_Cost_Typical', 'H_Cost_Mod',
       'T_Cost_Typical', 'T_Cost_Mod'],
      dtype='object', length=245)

In [8]:
for columns in full_comm_data.columns:
    print(columns)

GEOID
GEOG
2000_POP
2010_POP
TOT_POP
UND5
A5_19
A20_34
A35_49
A50_64
A65_74
A75_84
OV85
MED_AGE
WHITE
HISP
BLACK
ASIAN
OTHER
POP_HH
POP_16OV
IN_LBFRC
EMP
UNEMP
NOT_IN_LBFRC
TOT_WRKR16OV
WORK_AT_HOME
TOT_COMM
DROVE_AL
CARPOOL
TRANSIT
WALK_BIKE
COMM_OTHER
AGG_TT
NO_VEH
ONE_VEH
TWO_VEH
THREEOM_VEH
POP_25OV
LT_HS
HS
SOME_COLL
ASSOC
BACH
GRAD_PROF
INC_LT_25K
INC_25_50K
INC_50_75K
INC_75_100K
INC_100_150K
INC_GT_150
MEDINC
INCPERCAP
TOT_HH
OWN_OCC_HU
RENT_OCC_HU
VAC_HU
HU_TOT
HU_SNG_DET
HU_SNG_ATT
HU_2UN
HU_3_4UN
HU_5_9UN
HU_10_19UN
HU_GT_19UN
HU_MOBILE
MED_ROOMS
HA_AFT2000
HA_70_00
HA_40_70
HA_BEF1940
MED_HA
BR_0_1
BR_2
BR_3
BR_4
BR_5
HV_LT_150K
HV_150_300K
HV_300_500K
HV_GT_500K
MED_HV
CASHRENT_HH
RENT_LT500
RENT_500_999
RENT_1000_1499
RENT_1500_2499
RENT_GT2500
MED_RENT
COMPUTER
ONLY_SMARTPHONE
NO_COMPUTER
INTERNET
BROADBAND
NO_INTERNET
TOT_EMP_RES
RES_NAICS1_TYPE
RES_NAICS2_TYPE
RES_NAICS3_TYPE
RES_NAICS4_TYPE
RES_NAICS5_TYPE
RES_NAICS1_COUNT
RES_NAICS2_COUNT
RES_NAICS3_COUNT
RES_NAICS4_COUNT
RES_NAICS5_COUNT
TOT_EMP_WORK
WORK_NAICS1_TYPE
WORK_NAICS2_TYPE
WORK_NAICS3_TYPE
WORK_NAICS4_TYPE
WORK_NAICS5_TYPE
WORK_NAICS1_COUNT
WORK_NAICS2_COUNT
WORK_NAICS3_COUNT
WORK_NAICS4_COUNT
WORK_NAICS5_COUNT
RES_CITY1_TYPE
RES_CITY2_TYPE
RES_CITY3_TYPE
RES_CITY4_TYPE
RES_CITY5_TYPE
RES_CITY1_COUNT
RES_CITY2_COUNT
RES_CITY3_COUNT
RES_CITY4_COUNT
RES_CITY5_COUNT
WORK_CITY1_TYPE
WORK_CITY2_TYPE
WORK_CITY3_TYPE
WORK_CITY4_TYPE
WORK_CITY5_TYPE
WORK_CITY1_COUNT
WORK_CITY2_COUNT
WORK_CITY3_COUNT
WORK_CITY4_COUNT
WORK_CITY5_COUNT
IDES_START_EMP
IDES_MID_EMP
IDES_CURR_EMP
AVG_VMT
RET_SALES
GEN_MERCH
RES_EAV
CMRCL_EAV
IND_EAV
RAIL_EAV
FARM_EAV
MIN_EAV
TOT_EAV
TRANSIT_LOW_PCT
TRANSIT_MOD_PCT
TRANSIT_HIGH_PCT
WALKABLE_LOW_PCT
WALKABLE_MOD_PCT
WALKABLE_HIGH_PCT
OPEN_SPACE_PER_1000
TOT_ACRES
SF
Sfperc
MF
Mfperc
MIX
MIXperc
COMM
COMMperc
INST
INSTperc
IND
INDperc
TRANS
TRANSperc
AG
Agperc
OPEN
OPENperc
VACANT
VACperc
CT_1PHH
CT_2PHH
CT_3PHH
CT_4MPHH
CT_FAM_HH
CT_SP_WCHILD
CT_NONFAM_HH
HCUND20K
HCUND20K_LT20PCT
HCUND20K_20_29PCT
HCUND20K_30MPCT
HC20Kto49K
HC20Kto49K_LT20PCT
HC20Kto49K_20_29PCT
HC20Kto49K_30MPCT
HC50Kto75K
HC50Kto75K_LT20PCT
HC50Kto75K_20_29PCT
HC50Kto75K_30MPCT
HCOV75K
HCOV75K_LT20PCT
HCOV75K_20_29PCT
HCOV75K_30MPCT
NATIVE
FOR_BORN
POP_OV5
NOT_ENGLISH
LING_ISO
ENGLISH
SPANISH
SLAVIC
CHINESE
TAGALOG
ARABIC
KOREAN
OTHER_ASIAN
OTHER_EURO
OTHER_UNSPEC
2000_WHITE
2000_HISP
2000_BLACK
2000_ASIAN
2000_OTHER
2000_UND19
2000_A20_34
2000_A35_49
2000_A50_64
2000_OV65
2000_MED_AGE
2000_TOT_HH
2000_OWN_OCC_HU
2000_RENT_OCC_HU
2000_VAC_HU
2000_HU_TOT
2000_LT_HS
2000_HS
2000_SOME_COLL
2000_ASSOC
2000_BACH
2000_GRAD_PROF
2000_POP_25OV
HT_Cost_Typical
HT_Cost_Mod
H_Cost_Typical
H_Cost_Mod
T_Cost_Typical
T_Cost_Mod

In [9]:
prog_study_data=full_prog_data[['col_program_id',
                                'name',
                                'org_id',
                                'description',
                                'geographic_cluster_name',
                                'min_age',
                                'max_age',
                                'capacity',
                                'program_price',
                                'program_has_scholarships',
                                'program_provides_free_food',
                                'program_pays_participants',
                                'program_provides_transportation',
                                'category_name'
                               ]]

In [10]:
prog_study_data.head()

,col_program_id,name,org_id,description,geographic_cluster_name,min_age,max_age,capacity,program_price,program_has_scholarships,program_provides_free_food,program_pays_participants,program_provides_transportation,category_name
0,94395,Artist Development Music Program,18,<table><colgroup><col></colgroup><tbody><tr><t...,NaN,14,22,30.0,Free,0,NaN,"Paid, Type Unknown",0,Music & Art.
1,94405,Hoops in the Hood @ Back of the Yards,18,<table><colgroup><col></colgroup><tbody><tr><t...,NORTH LAWNDALE,16,22,5.0,Free,0,NaN,"Paid, Type Unknown",0,Helping Your Community.
2,99681,East Garfield Park Summer Kickback Event Augu...,1219,Join Breakthrough for the latest installment o...,NaN,13,24,0.0,Free,0,f,Not Paid,0,Music & Art.
3,94523,Paid Apprenticeships in Art + Technology,139,<p>Go to the After School Matters website and ...,NaN,15,18,NaN,Free,0,f,"Paid, Type Unknown",0,Work + Career
4,94238,Virtual Field Trip on Sustainability with Chic...,1449,"<p>Learn about plants, sustainability, and how...",AUSTIN,2,65,NaN,Free,0,f,Not Paid,0,Nature.

In [11]:
prog_study_data=prog_study_data.rename(columns={"geographic_cluster_name":"community_name"})

In [12]:
comm_study_data=full_comm_data[['GEOG',
                  '2010_POP',
                  'TOT_POP',
                  'UND5',
                  'A5_19',
                  'POP_16OV',
                  'INC_LT_25K',
                  'INC_25_50K',
                  'INC_50_75K',
                  'INC_75_100K',
                  'INC_100_150K',
                  'INC_GT_150',
                  'MEDINC',
                  'COMPUTER',
                  'ONLY_SMARTPHONE',
                  'NO_COMPUTER',
                  'INTERNET',
                  'BROADBAND',
                  'NO_INTERNET',
                  'NOT_ENGLISH',
                  'LING_ISO',
                  'ENGLISH',
                  'TRANSIT_LOW_PCT',
                  'TRANSIT_MOD_PCT',
                  'TRANSIT_HIGH_PCT',
                  'WALKABLE_LOW_PCT',
                  'WALKABLE_MOD_PCT',
                  'WALKABLE_HIGH_PCT'
]]

In [13]:
comm_study_data.head()

,GEOG,2010_POP,TOT_POP,UND5,A5_19,POP_16OV,INC_LT_25K,INC_25_50K,INC_50_75K,INC_75_100K,INC_100_150K,INC_GT_150,MEDINC,COMPUTER,ONLY_SMARTPHONE,NO_COMPUTER,INTERNET,BROADBAND,NO_INTERNET,NOT_ENGLISH,LING_ISO,ENGLISH,TRANSIT_LOW_PCT,TRANSIT_MOD_PCT,TRANSIT_HIGH_PCT,WALKABLE_LOW_PCT,WALKABLE_MOD_PCT,WALKABLE_HIGH_PCT
0,Albany Park,51542.0,49805.99998,3110.0,9413.0,39787.0,3037.0,3821.0,3000.0,2271.0,2623.0,2157.0,61759.0,15104.0,1262.0,1805.0,14235.0,13477.0,2674.0,28927.0,14419.0,17769.0,0.0,0.0,1.0,0.000000,0.000000,1.000000
1,Archer Heights,13393.0,13700.97018,1164.0,3306.0,10005.0,839.0,1098.0,758.0,361.0,636.0,223.0,50458.0,3203.0,253.0,711.0,3143.0,2882.0,771.0,10466.0,4639.0,2064.0,0.0,0.0,1.0,0.081438,0.000000,0.918562
2,Armour Square,13391.0,13598.48056,645.0,1876.0,11664.0,2434.0,1046.0,630.0,496.0,385.0,421.0,31663.0,4080.0,508.0,1333.0,3923.0,3689.0,1489.0,8994.0,6546.0,3952.0,0.0,0.0,1.0,0.000000,0.000000,1.000000
3,Ashburn,41081.0,43355.99999,2741.0,9956.0,33039.0,2266.0,2094.0,2730.0,2070.0,2498.0,1466.0,70223.0,11847.0,930.0,1277.0,11284.0,10442.0,1840.0,15101.0,4923.0,25514.0,0.0,0.0,1.0,0.000000,0.229628,0.770372
4,Auburn Gresham,48743.0,45909.00001,2415.0,9256.0,36568.0,6701.0,4402.0,2584.0,1439.0,1539.0,496.0,34396.0,13724.0,2356.0,3437.0,11879.0,10291.0,5282.0,1030.0,327.0,42464.0,0.0,0.0,1.0,0.000000,0.015820,0.984180

In [14]:
prog_study_data.shape

(4676, 14)

In [15]:
prog_study_data=prog_study_data.dropna()
prog_study_data.shape

(636, 14)

In [16]:
comm_study_data.shape

(104, 28)

In [17]:
comm_study_data=comm_study_data.dropna()
comm_study_data.shape

(77, 28)

In [18]:
#Capitalize the GEOG column to match cluster name column in prg data set
comm_study_data['GEOG']=comm_study_data['GEOG'].str.upper()

In [19]:
comm_study_data.head()

,GEOG,2010_POP,TOT_POP,UND5,A5_19,POP_16OV,INC_LT_25K,INC_25_50K,INC_50_75K,INC_75_100K,INC_100_150K,INC_GT_150,MEDINC,COMPUTER,ONLY_SMARTPHONE,NO_COMPUTER,INTERNET,BROADBAND,NO_INTERNET,NOT_ENGLISH,LING_ISO,ENGLISH,TRANSIT_LOW_PCT,TRANSIT_MOD_PCT,TRANSIT_HIGH_PCT,WALKABLE_LOW_PCT,WALKABLE_MOD_PCT,WALKABLE_HIGH_PCT
0,ALBANY PARK,51542.0,49805.99998,3110.0,9413.0,39787.0,3037.0,3821.0,3000.0,2271.0,2623.0,2157.0,61759.0,15104.0,1262.0,1805.0,14235.0,13477.0,2674.0,28927.0,14419.0,17769.0,0.0,0.0,1.0,0.000000,0.000000,1.000000
1,ARCHER HEIGHTS,13393.0,13700.97018,1164.0,3306.0,10005.0,839.0,1098.0,758.0,361.0,636.0,223.0,50458.0,3203.0,253.0,711.0,3143.0,2882.0,771.0,10466.0,4639.0,2064.0,0.0,0.0,1.0,0.081438,0.000000,0.918562
2,ARMOUR SQUARE,13391.0,13598.48056,645.0,1876.0,11664.0,2434.0,1046.0,630.0,496.0,385.0,421.0,31663.0,4080.0,508.0,1333.0,3923.0,3689.0,1489.0,8994.0,6546.0,3952.0,0.0,0.0,1.0,0.000000,0.000000,1.000000
3,ASHBURN,41081.0,43355.99999,2741.0,9956.0,33039.0,2266.0,2094.0,2730.0,2070.0,2498.0,1466.0,70223.0,11847.0,930.0,1277.0,11284.0,10442.0,1840.0,15101.0,4923.0,25514.0,0.0,0.0,1.0,0.000000,0.229628,0.770372
4,AUBURN GRESHAM,48743.0,45909.00001,2415.0,9256.0,36568.0,6701.0,4402.0,2584.0,1439.0,1539.0,496.0,34396.0,13724.0,2356.0,3437.0,11879.0,10291.0,5282.0,1030.0,327.0,42464.0,0.0,0.0,1.0,0.000000,0.015820,0.984180

In [20]:
prog_comm_study_df=pd.merge(prog_study_data,comm_study_data,how="left",left_on="community_name",right_on="GEOG").sort_values(by='col_program_id')

In [21]:
prog_comm_study_df.shape

(636, 42)

In [22]:
prog_comm_study_df.head()

,col_program_id,name,org_id,description,community_name,min_age,max_age,capacity,program_price,program_has_scholarships,program_provides_free_food,program_pays_participants,program_provides_transportation,category_name,GEOG,2010_POP,TOT_POP,UND5,A5_19,POP_16OV,INC_LT_25K,INC_25_50K,INC_50_75K,INC_75_100K,INC_100_150K,INC_GT_150,MEDINC,COMPUTER,ONLY_SMARTPHONE,NO_COMPUTER,INTERNET,BROADBAND,NO_INTERNET,NOT_ENGLISH,LING_ISO,ENGLISH,TRANSIT_LOW_PCT,TRANSIT_MOD_PCT,TRANSIT_HIGH_PCT,WALKABLE_LOW_PCT,WALKABLE_MOD_PCT,WALKABLE_HIGH_PCT
44,94180,BUILD Summer Camp 2021,11,"<p>-Six weeks of hands-on in-person, engaging ...",AUSTIN,6,14,60.0,Free,0,t,Not Paid,0,Music & Art.,AUSTIN,98514.0,93727.00001,6537.0,18270.0,73231.0,12869.0,8222.0,4375.0,2503.0,3177.0,1514.0,33515.0,25463.0,4365.0,7197.0,22856.0,21083.0,9804.0,12671.0,4139.0,74519.0,0.0,0.0,1.0,0.0,0.013927,0.986073
15,94180,BUILD Summer Camp 2021,11,"<p>-Six weeks of hands-on in-person, engaging ...",AUSTIN,6,14,60.0,Free,0,t,Not Paid,0,Sports + Wellness.,AUSTIN,98514.0,93727.00001,6537.0,18270.0,73231.0,12869.0,8222.0,4375.0,2503.0,3177.0,1514.0,33515.0,25463.0,4365.0,7197.0,22856.0,21083.0,9804.0,12671.0,4139.0,74519.0,0.0,0.0,1.0,0.0,0.013927,0.986073
0,94214,Inspirational Paper Mini Pennants Crafts Project,1239,<p>Make your very own flag of encouragement to...,AUSTIN,7,65,20.0,Free,0,f,Not Paid,0,Music & Art.,AUSTIN,98514.0,93727.00001,6537.0,18270.0,73231.0,12869.0,8222.0,4375.0,2503.0,3177.0,1514.0,33515.0,25463.0,4365.0,7197.0,22856.0,21083.0,9804.0,12671.0,4139.0,74519.0,0.0,0.0,1.0,0.0,0.013927,0.986073
55,94214,Inspirational Paper Mini Pennants Crafts Project,1239,<p>Make your very own flag of encouragement to...,AUSTIN,7,65,20.0,Free,0,f,Not Paid,0,Healthcare,AUSTIN,98514.0,93727.00001,6537.0,18270.0,73231.0,12869.0,8222.0,4375.0,2503.0,3177.0,1514.0,33515.0,25463.0,4365.0,7197.0,22856.0,21083.0,9804.0,12671.0,4139.0,74519.0,0.0,0.0,1.0,0.0,0.013927,0.986073
52,94215,URLife - Story Neighborhood Game,1239,<p>Join Lily Be in an interactive storytelling...,AUSTIN,7,65,12.0,Free,0,f,Not Paid,0,Music & Art.,AUSTIN,98514.0,93727.00001,6537.0,18270.0,73231.0,12869.0,8222.0,4375.0,2503.0,3177.0,1514.0,33515.0,25463.0,4365.0,7197.0,22856.0,21083.0,9804.0,12671.0,4139.0,74519.0,0.0,0.0,1.0,0.0,0.013927,0.986073

In [23]:
prog_comm_study_df.columns

Index(['col_program_id', 'name', 'org_id', 'description', 'community_name',
       'min_age', 'max_age', 'capacity', 'program_price',
       'program_has_scholarships', 'program_provides_free_food',
       'program_pays_participants', 'program_provides_transportation',
       'category_name', 'GEOG', '2010_POP', 'TOT_POP', 'UND5', 'A5_19',
       'POP_16OV', 'INC_LT_25K', 'INC_25_50K', 'INC_50_75K', 'INC_75_100K',
       'INC_100_150K', 'INC_GT_150', 'MEDINC', 'COMPUTER', 'ONLY_SMARTPHONE',
       'NO_COMPUTER', 'INTERNET', 'BROADBAND', 'NO_INTERNET', 'NOT_ENGLISH',
       'LING_ISO', 'ENGLISH', 'TRANSIT_LOW_PCT', 'TRANSIT_MOD_PCT',
       'TRANSIT_HIGH_PCT', 'WALKABLE_LOW_PCT', 'WALKABLE_MOD_PCT',
       'WALKABLE_HIGH_PCT'],
      dtype='object')

In [24]:
prog_comm_flat_category_df=prog_comm_study_df.groupby(['col_program_id', 'name', 'org_id', 'description', 'community_name',
       'min_age', 'max_age', 'capacity', 'program_price',
       'program_has_scholarships', 'program_provides_free_food',
       'program_pays_participants', 'program_provides_transportation','2010_POP', 'TOT_POP', 'UND5', 'A5_19',
       'POP_16OV', 'INC_LT_25K', 'INC_25_50K', 'INC_50_75K', 'INC_75_100K',
       'INC_100_150K', 'INC_GT_150', 'MEDINC', 'COMPUTER', 'ONLY_SMARTPHONE',
       'NO_COMPUTER', 'INTERNET', 'BROADBAND', 'NO_INTERNET', 'NOT_ENGLISH',
       'LING_ISO', 'ENGLISH', 'TRANSIT_LOW_PCT', 'TRANSIT_MOD_PCT',
       'TRANSIT_HIGH_PCT', 'WALKABLE_LOW_PCT', 'WALKABLE_MOD_PCT',
       'WALKABLE_HIGH_PCT'])['category_name'].apply(','.join).reset_index()

In [25]:
# Define database and collection
db = client.chi_prog_study
db.july_2021.drop()

In [26]:
collection = db.july_2021
prog_comm_study_df.reset_index(inplace=True)
data_dict = prog_comm_study_df.to_dict("records")
# Insert collection
collection.insert_many(data_dict)

In [ ]:
# Define database and collection
db = client.chi_prog_study
db.july_2021_flat.drop()

In [ ]:
collection = db.july_2021_flat
prog_comm_flat_category_df.reset_index(inplace=True)
data_dict = prog_comm_flat_category_df.to_dict("records")
# Insert collection
collection.insert_many(data_dict)